# run with
# cd ~/Development/forges-of-faith-backend
# docker-compose -f docker-compose-production.yml up -d
# or
# npm run docker:stack:up

version: "3.3"

services:
  # MongoDB service
  mongo:
    container_name: mongo
    image: mongo:latest
    restart: always
    volumes:
      - ./volumes/mongo/db:/data/db

  # Node API service
  api:
    container_name: api
    build: .
    ports:
      - 4000:3000
    env_file: .env.docker
    depends_on:
      - mongo

  # Web service
  web:
    container_name: web
    build:
      context: ../forges-of-faith-frontend
      dockerfile: Dockerfile
    ports:
      - 4001:8083
    env_file: .env.docker
    volumes:
      - .:/src
