# run with
# cd ~/Development/forges-of-faith-backend
# docker-compose -f docker-compose-production.yml up -d
# or
# npm run docker:stack:up

version: "3.3"

services:
  # Node API service
  api-dev:
    container_name: api-dev
    restart: unless-stopped
    build: .
    ports:
      - 5000:3001
    env_file: .env.docker

  # Web service
  web-dev:
    container_name: web-dev
    restart: unless-stopped
    build:
      context: ../begods-frontend
      dockerfile: Dockerfile
    ports:
      - 5001:8084
    env_file: .env.docker
    volumes:
      - .:/src
