version: "3.3"

services:
  api:
    container_name: api_dev
    restart: unless-stopped
    build:
      context: .
      args:
        - BRANCH=dev
    ports:
      - 5000:3001
    env_file: .env.dev
    depends_on:
      - mongo

  web:
    container_name: web_dev
    restart: unless-stopped
    build:
      context: ../forges-of-faith-frontend
      args:
        - BRANCH=dev
      dockerfile: Dockerfile
    ports:
      - 5001:8084
    env_file: .env.dev
    volumes:
      - ../forges-of-faith-frontend:/src

volumes:
  mongo_data: 