version: "3.3"

services:
  # MongoDB service
  mongo:
    container_name: mongo
    image: mongo:latest
    restart: unless-stopped
    ports:
      - 127.0.0.1:27017:27017
    volumes:
      - mongo_data:/data/db

  # Redis service
  redis:
    container_name: redis-container
    image: redis:latest
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    command: [ "redis-server", "--appendonly", "yes" ]

  # Node API service
  api:
    container_name: api
    restart: unless-stopped
    build: .
    ports:
      - 4000:3000
    env_file: .env.prod
    depends_on:
      - mongo
      - redis

  # Web service
  web:
    container_name: web
    restart: unless-stopped
    build:
      context: ../forges-of-faith-frontend
      dockerfile: Dockerfile
    ports:
      - 4001:8083
    env_file: .env.prod
    volumes:
      - .:/src

volumes:
  mongo_data:
  redis-data:
