export const countries = [
  { name: "Global", code: "NA", flag: "🌐", dialCode: "" },
  { name: "Afghanistan", code: "AFG", flag: "🇦🇫", dialCode: "+93" },
  { name: "Argentina", code: "ARG", flag: "🇦🇷", dialCode: "+54" },
  { name: "Australia", code: "AUS", flag: "🇦🇺", dialCode: "+61" },
  { name: "Azerbaijan", code: "AZE", flag: "🇦🇿", dialCode: "+994" },
  { name: "Bahamas", code: "BHS", flag: "🇧🇸", dialCode: "+1-242" },
  { name: "Bangladesh", code: "BGD", flag: "🇧🇩", dialCode: "+880" },
  { name: "Barbados", code: "BRB", flag: "🇧🇧", dialCode: "+1-246" },
  { name: "Belgium", code: "BEL", flag: "🇧🇪", dialCode: "+32" },
  { name: "Bhutan", code: "BTN", flag: "🇧🇹", dialCode: "+975" },
  { name: "Brazil", code: "BRA", flag: "🇧🇷", dialCode: "+55" },
  { name: "Canada", code: "CAN", flag: "🇨🇦", dialCode: "+1" },
  { name: "China", code: "CHN", flag: "🇨🇳", dialCode: "+86" },
  { name: "Colombia", code: "COL", flag: "🇨🇴", dialCode: "+57" },
  { name: "Denmark", code: "DNK", flag: "🇩🇰", dialCode: "+45" },
  { name: "Egypt", code: "EGY", flag: "🇪🇬", dialCode: "+20" },
  { name: "El Salvador", code: "SLV", flag: "🇸🇻", dialCode: "+503" },
  { name: "Finland", code: "FIN", flag: "🇫🇮", dialCode: "+358" },
  { name: "France", code: "FRA", flag: "🇫🇷", dialCode: "+33" },
  { name: "Gambia", code: "GMB", flag: "🇬🇲", dialCode: "+220" },
  { name: "Georgia", code: "GEO", flag: "🇬🇪", dialCode: "+995" },
  { name: "Germany", code: "DEU", flag: "🇩🇪", dialCode: "+49" },
  { name: "Greece", code: "GRC", flag: "🇬🇷", dialCode: "+30" },
  { name: "Hong Kong", code: "HKG", flag: "🇭🇰", dialCode: "+852" },
  { name: "Hungary", code: "HUN", flag: "🇭🇺", dialCode: "+36" },
  { name: "Iceland", code: "ISL", flag: "🇮🇸", dialCode: "+354" },
  { name: "India", code: "IND", flag: "🇮🇳", dialCode: "+91" },
  { name: "Indonesia", code: "IDN", flag: "🇮🇩", dialCode: "+62" },
  { name: "Iran", code: "IRN", flag: "🇮🇷", dialCode: "+98" },
  { name: "Iraq", code: "IRQ", flag: "🇮🇶", dialCode: "+964" },
  { name: "Ireland", code: "IRL", flag: "🇮🇪", dialCode: "+353" },
  { name: "Israel", code: "ISR", flag: "🇮🇱", dialCode: "+972" },
  { name: "Italy", code: "ITA", flag: "🇮🇹", dialCode: "+39" },
  { name: "Japan", code: "JPN", flag: "🇯🇵", dialCode: "+81" },
  { name: "Kenya", code: "KEN", flag: "🇰🇪", dialCode: "+254" },
  {
    name: "Korea, Democratic People's Republic of",
    code: "PRK",
    flag: "🇰🇵",
    dialCode: "+850",
  },
  { name: "Korea, Republic of", code: "KOR", flag: "🇰🇷", dialCode: "+82" },
  { name: "Luxembourg", code: "LUX", flag: "🇱🇺", dialCode: "+352" },
  { name: "Macao", code: "MAC", flag: "🇲🇴", dialCode: "+853" },
  { name: "Malaysia", code: "MYS", flag: "🇲🇾", dialCode: "+60" },
  { name: "Maldives", code: "MDV", flag: "🇲🇻", dialCode: "+960" },
  { name: "Mauritius", code: "MUS", flag: "🇲🇺", dialCode: "+230" },
  { name: "Mexico", code: "MEX", flag: "🇲🇽", dialCode: "+52" },
  { name: "Monaco", code: "MCO", flag: "🇲🇨", dialCode: "+377" },
  { name: "Myanmar", code: "MMR", flag: "🇲🇲", dialCode: "+95" },
  { name: "Namibia", code: "NAM", flag: "🇳🇦", dialCode: "+264" },
  { name: "Nepal", code: "NPL", flag: "🇳🇵", dialCode: "+977" },
  { name: "Netherlands", code: "NLD", flag: "🇳🇱", dialCode: "+31" },
  { name: "New Zealand", code: "NZL", flag: "🇳🇿", dialCode: "+64" },
  { name: "Nigeria", code: "NGA", flag: "🇳🇬", dialCode: "+234" },
  { name: "Norway", code: "NOR", flag: "🇳🇴", dialCode: "+47" },
  { name: "Pakistan", code: "PAK", flag: "🇵🇰", dialCode: "+92" },
  { name: "Peru", code: "PER", flag: "🇵🇪", dialCode: "+51" },
  { name: "Philippines", code: "PHL", flag: "🇵🇭", dialCode: "+63" },
  { name: "Poland", code: "POL", flag: "🇵🇱", dialCode: "+48" },
  { name: "Portugal", code: "PRT", flag: "🇵🇹", dialCode: "+351" },
  { name: "Qatar", code: "QAT", flag: "🇶🇦", dialCode: "+974" },
  { name: "Romania", code: "ROU", flag: "🇷🇴", dialCode: "+40" },
  { name: "Russian Federation", code: "RUS", flag: "🇷🇺", dialCode: "+7" },
  { name: "Saudi Arabia", code: "SAU", flag: "🇸🇦", dialCode: "+966" },
  { name: "Singapore", code: "SGP", flag: "🇸🇬", dialCode: "+65" },
  { name: "South Africa", code: "ZAF", flag: "🇿🇦", dialCode: "+27" },
  { name: "Spain", code: "ESP", flag: "🇪🇸", dialCode: "+34" },
  { name: "Sri Lanka", code: "LKA", flag: "🇱🇰", dialCode: "+94" },
  { name: "Sweden", code: "SWE", flag: "🇸🇪", dialCode: "+46" },
  { name: "Switzerland", code: "CHE", flag: "🇨🇭", dialCode: "+41" },
  {
    name: "Taiwan, Province of China",
    code: "TWN",
    flag: "🇹🇼",
    dialCode: "+886",
  },
  { name: "Tajikistan", code: "TJK", flag: "🇹🇯", dialCode: "+992" },
  { name: "Thailand", code: "THA", flag: "🇹🇭", dialCode: "+66" },
  { name: "Turkey", code: "TUR", flag: "🇹🇷", dialCode: "+90" },
  { name: "Uganda", code: "UGA", flag: "🇺🇬", dialCode: "+256" },
  { name: "Ukraine", code: "UKR", flag: "🇺🇦", dialCode: "+380" },
  { name: "United Arab Emirates", code: "ARE", flag: "🇦🇪", dialCode: "+971" },
  { name: "United Kingdom", code: "GBR", flag: "🇬🇧", dialCode: "+44" },
  { name: "United States", code: "USA", flag: "🇺🇸", dialCode: "+1" },
  { name: "Uzbekistan", code: "UZB", flag: "🇺🇿", dialCode: "+998" },
  { name: "Venezuela", code: "VEN", flag: "🇻🇪", dialCode: "+58" },
  { name: "Vietnam", code: "VNM", flag: "🇻🇳", dialCode: "+84" },
  { name: "Zambia", code: "ZMB", flag: "🇿🇲", dialCode: "+260" },
  { name: "Zimbabwe", code: "ZWE", flag: "🇿🇼", dialCode: "+263" },
];

export const validCountry = ["IND"];
