export const gameItems = [
  // potions
  { id: "potion.fire.A01", name: "potion", fragments: [0], coins: 4 },
  { id: "potion.fire.B01", name: "potion", fragments: [0], coins: 4 },
  { id: "potion.earth.A01", name: "potion", fragments: [0], coins: 4 },
  { id: "potion.earth.B01", name: "potion", fragments: [0], coins: 4 },
  { id: "potion.water.A01", name: "potion", fragments: [0], coins: 4 },
  { id: "potion.water.B01", name: "potion", fragments: [0], coins: 4 },
  { id: "potion.air.A01", name: "potion", fragments: [0], coins: 4 },
  { id: "potion.air.B01", name: "potion", fragments: [0], coins: 4 },
  { id: "potion.aether.A01", name: "potion", fragments: [0], coins: 9 },
  { id: "potion.aether.B01", name: "potion", fragments: [0], coins: 9 },

  // undeworld amulets
  {
    id: "underworld.artifact.treasure01-on",
    name: "sun amulet",
    fragments: [0],
    coins: 1,
  },
  {
    id: "underworld.artifact.treasure02-on",
    name: "moon amulet",
    fragments: [0],
    coins: 1,
  },

  // ======== CELTIC =======
  // celtic: relics
  {
    id: "celtic.relic.A01",
    name: "skean",
    fragments: [0, 1],
    coins: 3,
    orbs: "Celtic",
  },
  {
    id: "celtic.relic.A02",
    name: "lorg mor",
    fragments: [0, 1],
    coins: 3,
    orbs: "Celtic",
  },
  {
    id: "celtic.relic.A03",
    name: "gae bulg",
    fragments: [0, 1],
    coins: 3,
    orbs: "Egyptian",
  },
  {
    id: "celtic.relic.A04",
    name: "cliabh solais",
    fragments: [0, 1],
    coins: 2,
    orbs: "Celtic",
  },
  {
    id: "celtic.relic.A05",
    name: "fidbac",
    fragments: [0, 1],
    coins: 3,
    orbs: "Norse",
  },
  {
    id: "celtic.relic.A06",
    name: "ordus",
    fragments: [0, 1],
    coins: 2,
    orbs: "Greek",
  },
  {
    id: "celtic.relic.A07",
    name: "gae bulg",
    fragments: [0, 1],
    coins: 2,
    orbs: "Egyptian",
  },
  {
    id: "celtic.relic.A08",
    name: "fuip",
    fragments: [0, 1],
    coins: 2,
    orbs: "Celtic",
  },
  {
    id: "celtic.relic.A09",
    name: "uaithne",
    fragments: [0, 1],
    coins: 2,
    orbs: "Egyptian",
  },
  {
    id: "celtic.relic.B01",
    name: "gae dearg",
    fragments: [0, 1],
    coins: 3,
    orbs: "Celtic",
  },
  {
    id: "celtic.relic.B02",
    name: "shillelagh",
    fragments: [0, 1],
    coins: 3,
    orbs: "Celtic",
  },
  {
    id: "celtic.relic.B03",
    name: "conaire mor",
    fragments: [0, 1],
    coins: 3,
    orbs: "Greek",
  },
  {
    id: "celtic.relic.B04",
    name: "tuagh",
    fragments: [0, 1],
    coins: 2,
    orbs: "Celtic",
  },
  {
    id: "celtic.relic.B05",
    name: "muirgha",
    fragments: [0, 1],
    coins: 3,
    orbs: "Norse",
  },
  {
    id: "celtic.relic.B06",
    name: "cruach",
    fragments: [0, 1],
    coins: 2,
    orbs: "Aether",
  },
  {
    id: "celtic.relic.B07",
    name: "gae dearg",
    fragments: [0, 1],
    coins: 2,
    orbs: "Greek",
  },
  {
    id: "celtic.relic.B08",
    name: "samhain",
    fragments: [0, 1],
    coins: 2,
    orbs: "Norse",
  },
  {
    id: "celtic.relic.B09",
    name: "clairseach",
    fragments: [0, 1],
    coins: 2,
    orbs: "Egyptian",
  },
  {
    id: "celtic.relic.C00",
    name: "tech duinn",
    fragments: [0, 1],
    coins: 4,
    orbs: "Celtic",
  },
  {
    id: "celtic.relic.C01",
    name: "lamhainn",
    fragments: [0, 1],
    coins: 4,
    orbs: "Celtic",
  },
  {
    id: "celtic.relic.C02",
    name: "slabhra",
    fragments: [0, 1],
    coins: 3,
    orbs: "Celtic",
  },
  {
    id: "celtic.relic.C03",
    name: "coire ansic",
    fragments: [0, 1],
    coins: 3,
    orbs: "Aether",
  },
  {
    id: "celtic.relic.C04",
    name: "safach",
    fragments: [0, 1],
    coins: 2,
    orbs: "Norse",
  },
  {
    id: "celtic.relic.C05",
    name: "coil",
    fragments: [0, 1],
    coins: 2,
    orbs: "Norse",
  },
  {
    id: "celtic.relic.C06",
    name: "fealdog",
    fragments: [0],
    coins: 1,
    orbs: "Celtic",
  },
  {
    id: "celtic.relic.C07",
    name: "adharc",
    fragments: [0],
    coins: 1,
    orbs: "Celtic",
  },
  {
    id: "celtic.relic.C08",
    name: "cogar",
    fragments: [0],
    coins: 1,
    orbs: "Egyptian",
  },
  {
    id: "celtic.relic.C09",
    name: "edigh",
    fragments: [0, 1],
    coins: 3,
    orbs: "Aether",
  },

  // celtic: artifacts
  {
    id: "celtic.artifact.common01",
    name: "coin",
    fragments: [0],
    coins: 2,
  },
  { id: "celtic.artifact.common02", name: "key", fragments: [0], coins: 1 },
  { id: "celtic.artifact.common03", name: "boots", fragments: [0], coins: 1 },
  { id: "celtic.artifact.starter01", name: "statue", fragments: [0], coins: 1 },
  { id: "celtic.artifact.starter02", name: "map", fragments: [0], coins: 1 },
  {
    id: "celtic.artifact.starter03",
    name: "coin",
    fragments: [0],
    coins: 2,
  },
  {
    id: "celtic.artifact.starter04",
    name: "coin",
    fragments: [0],
    coins: 2,
  },
  {
    id: "celtic.artifact.starter05",
    name: "coin",
    fragments: [0],
    coins: 1,
  },
  {
    id: "celtic.artifact.starter06",
    name: "coin",
    fragments: [0],
    coins: 1,
  },
  {
    id: "celtic.artifact.starter07",
    name: "coin",
    fragments: [0],
    coins: 1,
  },
  {
    id: "celtic.artifact.starter08",
    name: "coin",
    fragments: [0],
    coins: 1,
  },
  {
    id: "celtic.artifact.starter09",
    name: "coin",
    fragments: [0],
    coins: 1,
  },
  { id: "celtic.artifact.starter10", name: "book", fragments: [0], coins: 1 },

  // celtic: tresures
  {
    id: "celtic.artifact.treasure01",
    name: "coin",
    fragments: [0],
    coins: 1,
  },

  // ======== EGYPTIAN =======
  // egyptian: relics
  {
    id: "egyptian.relic.A01",
    name: "ankh",
    fragments: [0, 1],
    coins: 3,
    orbs: "Egyptian",
  },
  {
    id: "egyptian.relic.A02",
    name: "rumh",
    fragments: [0, 1],
    coins: 3,
    orbs: "Egyptian",
  },
  {
    id: "egyptian.relic.A03",
    name: "harba",
    fragments: [0, 1],
    coins: 3,
    orbs: "Egyptian",
  },
  {
    id: "egyptian.relic.A04",
    name: "djed",
    fragments: [0, 1],
    coins: 2,
    orbs: "Celtic",
  },
  {
    id: "egyptian.relic.A05",
    name: "khanarjr",
    fragments: [0, 1],
    coins: 2,
    orbs: "Celtic",
  },
  {
    id: "egyptian.relic.A06",
    name: "hizam",
    fragments: [0, 1],
    coins: 2,
    orbs: "Aether",
  },
  {
    id: "egyptian.relic.A07",
    name: "ankh",
    fragments: [0, 1],
    coins: 2,
    orbs: "Egyptian",
  },
  {
    id: "egyptian.relic.A08",
    name: "al-mawt",
    fragments: [0, 1],
    coins: 2,
    orbs: "Norse",
  },
  {
    id: "egyptian.relic.A09",
    name: "dire",
    fragments: [0, 1],
    coins: 2,
    orbs: "Egyptian",
  },
  {
    id: "egyptian.relic.B0a",
    name: "kopesh",
    fragments: [0, 1],
    coins: 3,
    orbs: "Egyptian",
  },
  {
    id: "egyptian.relic.B02",
    name: "was",
    fragments: [0, 1],
    coins: 3,
    orbs: "Greek",
  },
  {
    id: "egyptian.relic.B03",
    name: "mateh",
    fragments: [0, 1],
    coins: 3,
    orbs: "Greek",
  },
  {
    id: "egyptian.relic.B04",
    name: "heka",
    fragments: [0, 1],
    coins: 2,
    orbs: "Greek",
  },
  {
    id: "egyptian.relic.B05",
    name: "alfatha",
    fragments: [0, 1],
    coins: 3,
    orbs: "Celtic",
  },
  {
    id: "egyptian.relic.B06",
    name: "sawlajan",
    fragments: [0, 1],
    coins: 2,
    orbs: "Celtic",
  },
  {
    id: "egyptian.relic.B07",
    name: "kopesh",
    fragments: [0, 1],
    coins: 2,
    orbs: "Egyptian",
  },
  {
    id: "egyptian.relic.B08",
    name: "nehasi",
    fragments: [0, 1],
    coins: 3,
    orbs: "Greek",
  },
  {
    id: "egyptian.relic.B09",
    name: "uraeus",
    fragments: [0, 1],
    coins: 2,
    orbs: "Norse",
  },
  {
    id: "egyptian.relic.C00",
    name: "duat",
    fragments: [0, 1],
    coins: 4,
    orbs: "Aether",
  },
  {
    id: "egyptian.relic.C01",
    name: "saif",
    fragments: [0, 1],
    coins: 4,
    orbs: "Egyptian",
  },
  {
    id: "egyptian.relic.C02",
    name: "fakhkh",
    fragments: [0, 1],
    coins: 3,
    orbs: "Egyptian",
  },
  {
    id: "egyptian.relic.C04",
    name: "tuq",
    fragments: [0, 1],
    coins: 3,
    orbs: "Aether",
  },
  {
    id: "egyptian.relic.C03",
    name: "sawt",
    fragments: [0, 1],
    coins: 2,
    orbs: "Celtic",
  },
  {
    id: "egyptian.relic.C05",
    name: "ney",
    fragments: [0, 1],
    coins: 2,
    orbs: "Celtic",
  },
  {
    id: "egyptian.relic.C06",
    name: "nekhakha",
    fragments: [0],
    coins: 1,
    orbs: "Greek",
  },
  {
    id: "egyptian.relic.C07",
    name: "baydah",
    fragments: [0],
    coins: 1,
    orbs: "Greek",
  },
  {
    id: "egyptian.relic.C08",
    name: "sistrum",
    fragments: [0],
    coins: 1,
    orbs: "Celtic",
  },
  {
    id: "egyptian.relic.C09",
    name: "khudha",
    fragments: [0],
    coins: 3,
    orbs: "Aether",
  },

  // egyptian: artifacts
  {
    id: "egyptian.artifact.common01",
    name: "coin",
    fragments: [0],
    coins: 2,
  },
  { id: "egyptian.artifact.common02", name: "key", fragments: [0], coins: 1 },
  { id: "egyptian.artifact.common03", name: "boots", fragments: [0], coins: 1 },
  {
    id: "egyptian.artifact.starter01",
    name: "statue",
    fragments: [0],
    coins: 1,
  },
  { id: "egyptian.artifact.starter02", name: "map", fragments: [0], coins: 1 },
  {
    id: "egyptian.artifact.starter03",
    name: "coin",
    fragments: [0],
    coins: 2,
  },
  {
    id: "egyptian.artifact.starter04",
    name: "coin",
    fragments: [0],
    coins: 2,
  },
  {
    id: "egyptian.artifact.starter05",
    name: "coin",
    fragments: [0],
    coins: 1,
  },
  {
    id: "egyptian.artifact.starter06",
    name: "coin",
    fragments: [0],
    coins: 1,
  },
  {
    id: "egyptian.artifact.starter07",
    name: "coin",
    fragments: [0],
    coins: 1,
  },
  {
    id: "egyptian.artifact.starter08",
    name: "coin",
    fragments: [0],
    coins: 1,
  },
  {
    id: "egyptian.artifact.starter09",
    name: "coin",
    fragments: [0],
    coins: 1,
  },
  { id: "egyptian.artifact.starter10", name: "book", fragments: [0], coins: 1 },

  // egyptian: tresures
  {
    id: "egyptian.artifact.treasure01",
    name: "coin",
    fragments: [0],
    coins: 1,
  },
  // ======== GREEK =======
  // greek: relics
  {
    id: "greek.relic.A01",
    name: "keravnos",
    fragments: [0, 1],
    coins: 3,
    orbs: "Greek",
  },
  {
    id: "greek.relic.A02",
    name: "ravdos",
    fragments: [0, 1],
    coins: 3,
    orbs: "Greek",
  },
  {
    id: "greek.relic.A03",
    name: "aegis",
    fragments: [0, 1],
    coins: 3,
    orbs: "Greek",
  },
  {
    id: "greek.relic.A04",
    name: "lyre",
    fragments: [0, 1],
    coins: 2,
    orbs: "Greek",
  },
  {
    id: "greek.relic.A05",
    name: "flagellum",
    fragments: [0, 1],
    coins: 2,
    orbs: "Greek",
  },
  {
    id: "greek.relic.A06",
    name: "khryselakatos",
    fragments: [0, 1],
    coins: 3,
    orbs: "Celtic",
  },
  {
    id: "greek.relic.A07",
    name: "aegis",
    fragments: [0, 1],
    coins: 2,
    orbs: "Greek",
  },
  {
    id: "greek.relic.A08",
    name: "chiton",
    fragments: [0, 1],
    coins: 2,
    orbs: "Celtic",
  },
  {
    id: "greek.relic.A09",
    name: "oenochoe",
    fragments: [0, 1],
    coins: 2,
    orbs: "Celtic",
  },
  {
    id: "greek.relic.B01",
    name: "drepani",
    fragments: [0, 1],
    coins: 3,
    orbs: "Greek",
  },
  {
    id: "greek.relic.B02",
    name: "bident",
    fragments: [0, 1],
    coins: 3,
    orbs: "Greek",
  },
  {
    id: "greek.relic.B03",
    name: "trident",
    fragments: [0, 1],
    coins: 3,
    orbs: "Norse",
  },
  {
    id: "greek.relic.B04",
    name: "xiphos",
    fragments: [0, 1],
    coins: 2,
    orbs: "Greek",
  },
  {
    id: "greek.relic.B05",
    name: "caduceus",
    fragments: [0, 1],
    coins: 3,
    orbs: "Aether",
  },
  {
    id: "greek.relic.B06",
    name: "cestus",
    fragments: [0, 1],
    coins: 2,
    orbs: "Norse",
  },
  {
    id: "greek.relic.B07",
    name: "xiphos",
    fragments: [0, 1],
    coins: 2,
    orbs: "Norse",
  },
  {
    id: "greek.relic.B08",
    name: "skiptro",
    fragments: [0, 1],
    coins: 2,
    orbs: "Aether",
  },
  {
    id: "greek.relic.B09",
    name: "sfyri",
    fragments: [0, 1],
    coins: 2,
    orbs: "Greek",
  },
  {
    id: "greek.relic.C00",
    name: "tartarus",
    fragments: [0, 1],
    coins: 4,
    orbs: "Aether",
  },
  {
    id: "greek.relic.C01",
    name: "chrysomats",
    fragments: [0, 1],
    coins: 4,
    orbs: "Greek",
  },
  {
    id: "greek.relic.C02",
    name: "alysida",
    fragments: [0, 1],
    coins: 3,
    orbs: "Greek",
  },
  {
    id: "greek.relic.C03",
    name: "chrysomallon",
    fragments: [0, 1],
    coins: 3,
    orbs: "Aether",
  },
  {
    id: "greek.relic.C04",
    name: "labrys",
    fragments: [0, 1],
    coins: 2,
    orbs: "Greek",
  },
  {
    id: "greek.relic.C05",
    name: "kathreftis",
    fragments: [0, 1],
    coins: 2,
    orbs: "Greek",
  },
  {
    id: "greek.relic.C06",
    name: "pistolotki",
    fragments: [0, 1],
    coins: 1,
    orbs: "Celtic",
  },
  {
    id: "greek.relic.C07",
    name: "mastigio",
    fragments: [0],
    coins: 1,
    orbs: "Greek",
  },
  {
    id: "greek.relic.C08",
    name: "kochyli",
    fragments: [0],
    coins: 1,
    orbs: "Norse",
  },
  {
    id: "greek.relic.C09",
    name: "kranos",
    fragments: [0],
    coins: 3,
    orbs: "Aether",
  },

  // greek: artifacts
  {
    id: "greek.artifact.common01",
    name: "coin",
    fragments: [0],
    coins: 2,
  },
  { id: "greek.artifact.common02", name: "key", fragments: [0], coins: 1 },
  { id: "greek.artifact.common03", name: "boots", fragments: [0], coins: 1 },
  { id: "greek.artifact.starter01", name: "statue", fragments: [0], coins: 1 },
  { id: "greek.artifact.starter02", name: "map", fragments: [0], coins: 1 },
  {
    id: "greek.artifact.starter03",
    name: "coin",
    fragments: [0],
    coins: 2,
  },
  {
    id: "greek.artifact.starter04",
    name: "coin",
    fragments: [0],
    coins: 2,
  },
  {
    id: "greek.artifact.starter05",
    name: "coin",
    fragments: [0],
    coins: 1,
  },
  {
    id: "greek.artifact.starter06",
    name: "coin",
    fragments: [0],
    coins: 1,
  },
  {
    id: "greek.artifact.starter07",
    name: "coin",
    fragments: [0],
    coins: 1,
  },
  {
    id: "greek.artifact.starter08",
    name: "coin",
    fragments: [0],
    coins: 1,
  },
  {
    id: "greek.artifact.starter09",
    name: "coin",
    fragments: [0],
    coins: 1,
  },
  { id: "greek.artifact.starter10", name: "book", fragments: [0], coins: 1 },

  // greek: tresures
  {
    id: "greek.artifact.treasure01",
    name: "coin",
    fragments: [0],
    coins: 1,
  },

  // ======== NORSE =======
  // norse: relics
  {
    id: "norse.relic.A01",
    name: "gungnir",
    fragments: [0, 1],
    coins: 3,
    orbs: "Norse",
  },
  {
    id: "norse.relic.A02",
    name: "mjolnir",
    fragments: [0, 1],
    coins: 3,
    orbs: "Greek",
  },
  {
    id: "norse.relic.A03",
    name: "hofud",
    fragments: [0, 1],
    coins: 3,
    orbs: "Norse",
  },
  {
    id: "norse.relic.A04",
    name: "kona",
    fragments: [0, 1],
    coins: 2,
    orbs: "Greek",
  },
  {
    id: "norse.relic.A05",
    name: "hammar",
    fragments: [0, 1],
    coins: 2,
    orbs: "Greek",
  },
  {
    id: "norse.relic.A06",
    name: "eldrskjold",
    fragments: [0, 1],
    coins: 2,
    orbs: "Norse",
  },
  {
    id: "norse.relic.A07",
    name: "GUNGNIR",
    fragments: [0, 1],
    coins: 2,
    orbs: "Greek",
  },
  {
    id: "norse.relic.A08",
    name: "hunbogi",
    fragments: [0, 1],
    coins: 3,
    orbs: "Norse",
  },
  {
    id: "norse.relic.A09",
    name: "skoldr",
    fragments: [0, 1],
    coins: 2,
    orbs: "Celtic",
  },
  {
    id: "norse.relic.B01",
    name: "stridclub",
    fragments: [0, 1],
    coins: 3,
    orbs: "Norse",
  },
  {
    id: "norse.relic.B02",
    name: "laevateinn",
    fragments: [0, 1],
    coins: 3,
    orbs: "Norse",
  },
  {
    id: "norse.relic.B03",
    name: "svallin vondr",
    fragments: [0, 1],
    coins: 3,
    orbs: "Aether",
  },
  {
    id: "norse.relic.B04",
    name: "LAEVATEINN",
    fragments: [0, 1],
    coins: 2,
    orbs: "Aether",
  },
  {
    id: "norse.relic.B05",
    name: "atgear",
    fragments: [0, 1],
    coins: 2,
    orbs: "Norse",
  },
  {
    id: "norse.relic.B06",
    name: "skadejarn",
    fragments: [0, 1],
    coins: 3,
    orbs: "Greek",
  },
  {
    id: "norse.relic.B07",
    name: "SVALLIN-VONDR",
    fragments: [0, 1],
    coins: 2,
    orbs: "Greek",
  },
  {
    id: "norse.relic.B08",
    name: "eikthyrnir",
    fragments: [0, 1],
    coins: 2,
    orbs: "Celtic",
  },
  {
    id: "norse.relic.B09",
    name: "flengja",
    fragments: [0, 1],
    coins: 2,
    orbs: "Celtic",
  },
  {
    id: "norse.relic.C00",
    name: "ragnarok",
    fragments: [0, 1],
    coins: 4,
    orbs: "Aether",
  },
  {
    id: "norse.relic.C01",
    name: "angurvadal",
    fragments: [0, 1],
    coins: 4,
    orbs: "Norse",
  },
  {
    id: "norse.relic.C02",
    name: "taug",
    fragments: [0, 1],
    coins: 2,
    orbs: "Norse",
  },
  {
    id: "norse.relic.C03",
    name: "seidrkista",
    fragments: [0, 1],
    coins: 3,
    orbs: "Aether",
  },
  {
    id: "norse.relic.C04",
    name: "gleipnir",
    fragments: [0, 1],
    coins: 3,
    orbs: "Norse",
  },
  {
    id: "norse.relic.C05",
    name: "pottr",
    fragments: [0, 1],
    coins: 2,
    orbs: "Celtic",
  },
  {
    id: "norse.relic.C06",
    name: "bjalla",
    fragments: [0],
    coins: 1,
    orbs: "Cetic",
  },
  {
    id: "norse.relic.C07",
    name: "keyra",
    fragments: [0],
    coins: 1,
    orbs: "Greek",
  },
  {
    id: "norse.relic.C08",
    name: "kraviklyra",
    fragments: [0],
    coins: 1,
    orbs: "Greek",
  },
  {
    id: "norse.relic.C09",
    name: "hjelm",
    fragments: [0, 1],
    coins: 3,
    orbs: "Aether",
  },

  // norse: artifacts
  {
    id: "norse.artifact.common01",
    name: "coin",
    fragments: [0],
    coins: 2,
  },
  { id: "norse.artifact.common02", name: "key", fragments: [0], coins: 1 },
  { id: "norse.artifact.common03", name: "boots", fragments: [0], coins: 1 },
  { id: "norse.artifact.starter01", name: "statue", fragments: [0], coins: 1 },
  { id: "norse.artifact.starter02", name: "map", fragments: [0], coins: 1 },
  {
    id: "norse.artifact.starter03",
    name: "coin",
    fragments: [0],
    coins: 2,
  },
  {
    id: "norse.artifact.starter04",
    name: "coin",
    fragments: [0],
    coins: 2,
  },
  {
    id: "norse.artifact.starter05",
    name: "coin",
    fragments: [0],
    coins: 1,
  },
  {
    id: "norse.artifact.starter06",
    name: "coin",
    fragments: [0],
    coins: 1,
  },
  {
    id: "norse.artifact.starter07",
    name: "coin",
    fragments: [0],
    coins: 1,
  },
  {
    id: "norse.artifact.starter08",
    name: "coin",
    fragments: [0],
    coins: 1,
  },
  {
    id: "norse.artifact.starter09",
    name: "coin",
    fragments: [0],
    coins: 1,
  },
  { id: "norse.artifact.starter10", name: "book", fragments: [0], coins: 1 },

  // norse: tresures
  {
    id: "norse.artifact.treasure01",
    name: "coin",
    fragments: [0],
    coins: 1,
  },
];
