export const country = [
  { name: "Global", code: "NA" },
  { name: "Afghanistan", code: "AFG" },
  { name: "Argentina", code: "ARG" },
  { name: "Australia", code: "AUS" },
  { name: "Azerbaijan", code: "AZE" },
  { name: "Bahamas", code: "BHS" },
  { name: "Bangladesh", code: "BGD" },
  { name: "Barbados", code: "BRB" },
  { name: "Belgium", code: "BEL" },
  { name: "Bhutan", code: "BTN" },
  { name: "Brazil", code: "BRA" },
  { name: "Canada", code: "CAN" },
  { name: "China", code: "CHN" },
  { name: "Colombia", code: "COL" },
  { name: "Denmark", code: "DNK" },
  { name: "Egypt", code: "EGY" },
  { name: "El Salvador", code: "SLV" },
  { name: "Finland", code: "FIN" },
  { name: "France", code: "FRA" },
  { name: "Gambia", code: "GMB" },
  { name: "Georgia", code: "GEO" },
  { name: "Germany", code: "DEU" },
  { name: "Greece", code: "GRC" },
  { name: "Hong Kong", code: "HKG" },
  { name: "Hungary", code: "HUN" },
  { name: "Iceland", code: "ISL" },
  { name: "India", code: "IND" },
  { name: "Indonesia", code: "IDN" },
  { name: "Iran", code: "IRN" },
  { name: "Iraq", code: "IRQ" },
  { name: "Ireland", code: "IRL" },
  { name: "Israel", code: "ISR" },
  { name: "Italy", code: "ITA" },
  { name: "Japan", code: "JPN" },
  { name: "Kenya", code: "KEN" },
  { name: "Korea, Democratic People's Republic of", code: "PRK" },
  { name: "Korea, Republic of", code: "KOR" },
  { name: "Luxembourg", code: "LUX" },
  { name: "Macao", code: "MAC" },
  { name: "Malaysia", code: "MYS" },
  { name: "Maldives", code: "MDV" },
  { name: "Mauritius", code: "MUS" },
  { name: "Mexico", code: "MEX" },
  { name: "Monaco", code: "MCO" },
  { name: "Myanmar", code: "MMR" },
  { name: "Namibia", code: "NAM" },
  { name: "Nepal", code: "NPL" },
  { name: "Netherlands", code: "NLD" },
  { name: "New Zealand", code: "NZL" },
  { name: "Nigeria", code: "NGA" },
  { name: "Norway", code: "NOR" },
  { name: "Pakistan", code: "PAK" },
  { name: "Peru", code: "PER" },
  { name: "Philippines", code: "PHL" },
  { name: "Poland", code: "POL" },
  { name: "Portugal", code: "PRT" },
  { name: "Qatar", code: "QAT" },
  { name: "Romania", code: "ROU" },
  { name: "Russian Federation", code: "RUS" },
  { name: "Saudi Arabia", code: "SAU" },
  { name: "Singapore", code: "SGP" },
  { name: "South Africa", code: "ZAF" },
  { name: "Spain", code: "ESP" },
  { name: "Sri Lanka", code: "LKA" },
  { name: "Sweden", code: "SWE" },
  { name: "Switzerland", code: "CHE" },
  { name: "Taiwan, Province of China", code: "TWN" },
  { name: "Tajikistan", code: "TJK" },
  { name: "Thailand", code: "THA" },
  { name: "Turkey", code: "TUR" },
  { name: "Uganda", code: "UGA" },
  { name: "Ukraine", code: "UKR" },
  { name: "United Arab Emirates", code: "ARE" },
  { name: "United Kingdom", code: "GBR" },
  { name: "United States", code: "USA" },
  { name: "Uzbekistan", code: "UZB" },
  { name: "Vietnam", code: "VNM" },
  { name: "Zambia", code: "ZMB" },
  { name: "Zimbabwe", code: "ZWE" },
];
