export const defaultMythologies = [
  {
    name: "Celtic",
    orbs: 0,
    shards: 0,
    tapSessionStartTime: 0,
    lastTapAcitivityTime: Date.now(),
    energy: 1000,
    energyLimit: 1000,
    faith: 0,
    boosters: {
      shardslvl: 1,
      shardsLastClaimedAt: 0,
      isShardsClaimActive: true,
      automataLastClaimedAt: 0,
      isAutomataActive: false,
      automataStartTime: 0,
    },
  },
  {
    name: "Egyptian",
    orbs: 0,
    shards: 0,
    tapSessionStartTime: 0,
    lastTapAcitivityTime: Date.now(),
    energy: 1000,
    energyLimit: 1000,
    faith: 0,
    boosters: {
      shardslvl: 1,
      shardsLastClaimedAt: 0,
      isShardsClaimActive: true,
      automataLastClaimedAt: 0,
      isAutomataActive: false,
      automataStartTime: 0,
    },
  },
  {
    name: "Greek",
    orbs: 0,
    shards: 0,
    tapSessionStartTime: 0,
    lastTapAcitivityTime: Date.now(),
    energy: 1000,
    energyLimit: 1000,
    faith: 0,
    boosters: {
      shardslvl: 1,
      shardsLastClaimedAt: 0,
      isShardsClaimActive: true,
      automataLastClaimedAt: 0,
      isAutomataActive: false,
      automataStartTime: 0,
    },
  },
  {
    name: "Norse",
    orbs: 0,
    shards: 0,
    tapSessionStartTime: 0,
    lastTapAcitivityTime: Date.now(),
    energy: 1000,
    energyLimit: 1000,
    faith: 0,
    boosters: {
      shardslvl: 1,
      shardsLastClaimedAt: 0,
      isShardsClaimActive: true,
      automataLastClaimedAt: 0,
      isAutomataActive: false,
      automataStartTime: 0,
    },
  },
];
